export interface CharMapping {
  pinyin: string;
  traditional: string;
  martian: string;
}

// 常用次文化汉字简体、繁体、火星文、拼音字典
export const CHAR_DB: Record<string, CharMapping> = {
  "雪": { pinyin: "xue", traditional: "雪", martian: "膤" },
  "芝": { pinyin: "zhi", traditional: "芝", martian: "芝" },
  "麻": { pinyin: "ma", traditional: "麻", martian: "嘛" },
  "糊": { pinyin: "hu", traditional: "糊", martian: "糊" },
  "我": { pinyin: "wo", traditional: "我", martian: "涐" },
  "你": { pinyin: "ni", traditional: "你", martian: "伱" },
  "他": { pinyin: "ta", traditional: "他", martian: "彵" },
  "她": { pinyin: "ta", traditional: "她", martian: "咜" },
  "它": { pinyin: "ta", traditional: "它", martian: "牠" },
  "们": { pinyin: "men", traditional: "們", martian: "們" },
  "爱": { pinyin: "ai", traditional: "愛", martian: "噯" },
  "情": { pinyin: "qing", traditional: "情", martian: "情" },
  "痛": { pinyin: "tong", traditional: "痛", martian: "痌" },
  "心": { pinyin: "xin", traditional: "心", martian: "惢" },
  "伤": { pinyin: "shang", traditional: "傷", martian: "傷" },
  "碎": { pinyin: "sui", traditional: "碎", martian: "誶" },
  "天": { pinyin: "tian", traditional: "天", martian: "迗" },
  "地": { pinyin: "di", traditional: "地", martian: "哋" },
  "人": { pinyin: "ren", traditional: "人", martian: "亾" },
  "神": { pinyin: "shen", traditional: "神", martian: "榊" },
  "魔": { pinyin: "mo", traditional: "魔", martian: "嚤" },
  "仙": { pinyin: "xian", traditional: "仙", martian: "仚" },
  "鬼": { pinyin: "gui", traditional: "鬼", martian: "鬼" },
  "妖": { pinyin: "yao", traditional: "妖", martian: "妖" },
  "狂": { pinyin: "kuang", traditional: "狂", martian: "狂" },
  "霸": { pinyin: "ba", traditional: "霸", martian: "灞" },
  "爷": { pinyin: "ye", traditional: "爷", martian: "爺" },
  "奶": { pinyin: "nai", traditional: "奶", martian: "奶" },
  "爸": { pinyin: "ba", traditional: "爸", martian: "爸" },
  "妈": { pinyin: "ma", traditional: "媽", martian: "媽" },
  "哥": { pinyin: "ge", traditional: "哥", martian: "滒" },
  "姐": { pinyin: "jie", traditional: "姐", martian: "姊" },
  "弟": { pinyin: "di", traditional: "弟", martian: "弚" },
  "妹": { pinyin: "mei", traditional: "妹", martian: "妺" },
  "大": { pinyin: "da", traditional: "大", martian: "宱" },
  "小": { pinyin: "xiao", traditional: "小", martian: "尐" },
  "多": { pinyin: "duo", traditional: "多", martian: "誃" },
  "少": { pinyin: "shao", traditional: "少", martian: "仯" },
  "美": { pinyin: "mei", traditional: "美", martian: "羙" },
  "丑": { pinyin: "chou", traditional: "醜", martian: "醜" },
  "真": { pinyin: "zhen", traditional: "真", martian: "眞" },
  "假": { pinyin: "jia", traditional: "假", martian: "叚" },
  "是": { pinyin: "shi", traditional: "是", martian: "昰" },
  "非": { pinyin: "fei", traditional: "非", martian: "悱" },
  "好": { pinyin: "hao", traditional: "好", martian: "恏" },
  "坏": { pinyin: "huai", traditional: "壞", martian: "壞" },
  "乐": { pinyin: "le", traditional: "樂", martian: "楽" },
  "悲": { pinyin: "bei", traditional: "悲", martian: "暃" },
  "喜": { pinyin: "xi", traditional: "喜", martian: "囍" },
  "怒": { pinyin: "nu", traditional: "怒", martian: "囦" },
  "哀": { pinyin: "ai", traditional: "哀", martian: "哀" },
  "笑": { pinyin: "xiao", traditional: "笑", martian: "咲" },
  "哭": { pinyin: "ku", traditional: "哭", martian: "泶" },
  "梦": { pinyin: "meng", traditional: "夢", martian: "儚" },
  "幻": { pinyin: "huan", traditional: "幻", martian: "幻" },
  "影": { pinyin: "ying", traditional: "影", martian: "影" },
  "光": { pinyin: "guang", traditional: "光", martian: "洸" },
  "暗": { pinyin: "an", traditional: "暗", martian: "闇" },
  "星": { pinyin: "xing", traditional: "星", martian: "暒" },
  "月": { pinyin: "yue", traditional: "月", martian: "玥" },
  "日": { pinyin: "ri", traditional: "日", martian: "ㄖ" },
  "风": { pinyin: "feng", traditional: "風", martian: "沨" },
  "雨": { pinyin: "yu", traditional: "雨", martian: "雨" },
  "雷": { pinyin: "lei", traditional: "雷", martian: "靁" },
  "电": { pinyin: "dian", traditional: "電", martian: "電" },
  "冰": { pinyin: "bing", traditional: "冰", martian: "氷" },
  "火": { pinyin: "huo", traditional: "火", martian: "焱" },
  "水": { pinyin: "shui", traditional: "水", martian: "淼" },
  "土": { pinyin: "tu", traditional: "土", martian: "圡" },
  "金": { pinyin: "jin", traditional: "金", martian: "鑫" },
  "木": { pinyin: "mu", traditional: "木", martian: "森" },
  "石": { pinyin: "shi", traditional: "石", martian: "鉐" },
  "沙": { pinyin: "sha", traditional: "沙", martian: "唦" },
  "海": { pinyin: "hai", traditional: "海", martian: "嗨" },
  "洋": { pinyin: "yang", traditional: "洋", martian: "烊" },
  "山": { pinyin: "shan", traditional: "山", martian: "屾" },
  "川": { pinyin: "chuan", traditional: "川", martian: "巛" },
  "空": { pinyin: "kong", traditional: "空", martian: "倥" },
  "白": { pinyin: "bai", traditional: "白", martian: "咟" },
  "黑": { pinyin: "hei", traditional: "黑", martian: "潶" },
  "红": { pinyin: "hong", traditional: "紅", martian: "糸" },
  "绿": { pinyin: "lv", traditional: "綠", martian: "綠" },
  "蓝": { pinyin: "lan", traditional: "藍", martian: "藍" },
  "黄": { pinyin: "huang", traditional: "黃", martian: "黃" },
  "紫": { pinyin: "zi", traditional: "紫", martian: "紫" },
  "粉": { pinyin: "fen", traditional: "粉", martian: "粉" },
  "青": { pinyin: "qing", traditional: "青", martian: "靑" },
  "橙": { pinyin: "cheng", traditional: "橙", martian: "橙" },
  "灰": { pinyin: "hui", traditional: "灰", martian: "烣" },
  "丝": { pinyin: "si", traditional: "絲", martian: "絲" },
  "瓜": { pinyin: "gua", traditional: "瓜", martian: "瓜" },
  "卡": { pinyin: "ka", traditional: "卡", martian: "咔" },
  "夫": { pinyin: "fu", traditional: "夫", martian: "夫" },
  "拂": { pinyin: "fu", traditional: "拂", martian: "拂" },
  "晓": { pinyin: "xiao", traditional: "曉", martian: "暁" },
  "之": { pinyin: "zhi", traditional: "之", martian: "の" },
  "间": { pinyin: "jian", traditional: "間", martian: "間" },
  "猫": { pinyin: "mao", traditional: "貓", martian: "猫" },
  "狗": { pinyin: "gou", traditional: "狗", martian: "狗" },
  "姬": { pinyin: "ji", traditional: "姬", martian: "姬" },
  "王": { pinyin: "wang", traditional: "王", martian: "王" },
  "圣": { pinyin: "sheng", traditional: "聖", martian: "聖" },
  "剑": { pinyin: "jian", traditional: "劍", martian: "剣" },
  "奇": { pinyin: "qi", traditional: "奇", martian: "奇" },
  "士": { pinyin: "shi", traditional: "士", martian: "士" },
  "女": { pinyin: "nv", traditional: "女", martian: "女" },
  "使": { pinyin: "shi", traditional: "使", martian: "使" },
  "恶": { pinyin: "e", traditional: "惡", martian: "惡" },
  "夜": { pinyin: "ye", traditional: "夜", martian: "夜" },
  "樱": { pinyin: "ying", traditional: "櫻", martian: "桜" },
  "羽": { pinyin: "yu", traditional: "羽", martian: "羽" },
  "翼": { pinyin: "yi", traditional: "翼", martian: "翼" },
  "音": { pinyin: "yin", traditional: "音", martian: "音" },
  "酱": { pinyin: "jiang", traditional: "醬", martian: "醬" },
  "君": { pinyin: "jun", traditional: "君", martian: "君" },
  "子": { pinyin: "zi", traditional: "子", martian: "子" },
  "无": { pinyin: "wu", traditional: "無", martian: "無" },
  "敌": { pinyin: "di", traditional: "敵", martian: "敵" },
  "超": { pinyin: "chao", traditional: "超", martian: "超" },
  "级": { pinyin: "ji", traditional: "級", martian: "級" },
  "元": { pinyin: "yuan", traditional: "元", martian: "元" },
  "气": { pinyin: "qi", traditional: "氣", martian: "氣" },
  "傲": { pinyin: "ao", traditional: "傲", martian: "傲" },
  "娇": { pinyin: "jiao", traditional: "嬌", martian: "嬌" },
  "特": { pinyin: "te", traditional: "特", martian: "特" },
  "野": { pinyin: "ye", traditional: "野", martian: "野" },
  "生": { pinyin: "sheng", traditional: "生", martian: "生" },
  "闪": { pinyin: "shan", traditional: "閃", martian: "閃" },
  "耀": { pinyin: "yao", traditional: "耀", martian: "耀" },
  "绝": { pinyin: "jue", traditional: "絕", martian: "絕" },
  "版": { pinyin: "ban", traditional: "版", martian: "版" },
  "一": { pinyin: "yi", traditional: "一", martian: "弌" },
  "只": { pinyin: "zhi", traditional: "只", martian: "只" },
  "糖": { pinyin: "tang", traditional: "糖", martian: "糖" },
  "醋": { pinyin: "cu", traditional: "醋", martian: "醋" },
  "鱼": { pinyin: "yu", traditional: "魚", martian: "魚" },
  "肉": { pinyin: "rou", traditional: "肉", martian: "肉" },
  "排": { pinyin: "pai", traditional: "排", martian: "排" },
  "骨": { pinyin: "gu", traditional: "骨", martian: "骨" },
  "茶": { pinyin: "cha", traditional: "茶", martian: "茶" },
  "咖": { pinyin: "ka", traditional: "咖", martian: "咖" },
  "啡": { pinyin: "fei", traditional: "啡", martian: "啡" },
  "可": { pinyin: "ke", traditional: "可", martian: "可" },
  "薯": { pinyin: "shu", traditional: "薯", martian: "薯" },
  "条": { pinyin: "tiao", traditional: "條", martian: "條" },
  "片": { pinyin: "pian", traditional: "片", martian: "片" }
};

export interface AffixItem {
  left: string;
  right: string;
  type: string;
}

// 预设前缀与后缀
const rawPrefixes = [
  "野生", "无敌", "究极", "闪光", "元气", "绝版", "傲娇", "特级", "超级", "一只",
  "爆裂", "致命", "软萌", "极客", "咸鱼", "咕咕", "傲世", "幻影", "终焉", "虚无",
  "傲雪", "绯红", "幽冥", "极光", "绝望", "纯情", "快乐", "腹黑", "中二", "傲慢",
  "深渊", "苍穹", "傲天", "独行", "冰封", "烈焰"
];

const rawSuffixes = [
  "酱", "子", "君", "の", "sama", "殿", "喵", "qwq", "awa", "ovo",
  "哒", "咩", "啵", "叽", "噗", "嗷", "吼", "啾", "控", "姬",
  "兽", "王", "狂", "神", "仙", "尊", "霸", "皇", "爷", "仔",
  "宝", "糖", "梦", "妖", "灵", "星"
];

// 火星文两端随机修饰符
const rawMartian = [
  { left: "oοО", right: "Оοo" },
  { left: "灬", right: "灬" },
  { left: "☆ミ", right: "彡☆" },
  { left: "★`", right: "´★" },
  { left: "°【", right: "】°" },
  { left: "✿", right: "✿" },
  { left: "ゞ", right: "ゞ" },
  { left: "〆", right: "〆" },
  { left: "₊°✢ε৯", right: "໒३✢°₊" },
  { left: "꧁", right: "꧂" },
  { left: "❦", right: "❦" },
  { left: "๑۩۞۩๑", right: "๑۩۞۩๑" },
  { left: "◤", right: "◢" },
  { left: "ღ", right: "ღ" },
  { left: "ஐ", right: "ஐ" },
  { left: "๑", right: "๑" },
  { left: "☣", right: "☣" },
  { left: "☠", right: "☠" },
  { left: "☯", right: "☯" },
  { left: "☪", right: "☪" },
  { left: "❂", right: "❂" },
  { left: "❃", right: "❃" },
  { left: "❉", right: "❉" },
  { left: "☄", right: "☄" },
  { left: "⚡", right: "⚡" },
  { left: "⚓", right: "⚓" },
  { left: "✿☉", right: "☉✿" },
  { left: "۞", right: "۞" },
  { left: "❖", right: "❖" },
  { left: "❧", right: "❧" },
  { left: "❣", right: "❣" },
  { left: "✉", right: "✉" },
  { left: "❆", right: "❆" },
  { left: "☾", right: "☽" },
  { left: "☆º°˚", right: "˚°º☆" },
  { left: "◇◆", right: "◆◇" }
];

export const BUILTIN_AFFIXES: AffixItem[] = [
  ...rawPrefixes.map(p => ({ left: p, right: "", type: "prefix" })),
  ...rawSuffixes.map(s => ({ left: "", right: s, type: "suffix" })),
  ...rawMartian.map(m => ({ left: m.left, right: m.right, type: "martian" }))
];

// Leetspeak 英文字母映射表
export const LEET_MAP: Record<string, string> = {
  "a": "4", "b": "8", "e": "3", "g": "6", "i": "1", "o": "0", "s": "5", "t": "7", "z": "2",
  "A": "4", "B": "8", "E": "3", "G": "6", "I": "1", "O": "0", "S": "5", "T": "7", "Z": "2"
};

